[project]
name = "clean_dns"
version = "0.1.0"
description = "The purpose of this project is to use Python to manage Domain Name System (DNS) zone files."
readme = "README.md"
dependencies = [
    "dnspython",
    "packaging",
    "pefile",
    "pywin32-ctypes",
    "setuptools",
    "pytest",
    "pyinstaller"
]
[project.scripts]
cleandns = "cleandns.main:main"
